keymap:
  descend_stairs: [".", "<"]
  rest: ["KP5"]
  eat_food: ["e"]
  wear_armor: ["W"]
  wield_a_weapon: ["w"]
  put_on_a_ring: ["P"]
  debug_mode: ["@", "SHIFT+2"]
  inspect_item: ["i"]
  help: ["?", "SHIFT+h"]
  save_game: ["F1"]
  load_game: ["F2"]
  console_mode: ["F12"]
